ethereum_package:
  participants:
    - el_type: reth
      el_extra_params:
        - "--rpc.eth-proof-window 100"
      cl_type: lighthouse
optimism_package:
  chains:
    - participants:
      - el_type: op-reth
        el_image: "ghcr.io/paradigmxyz/op-reth:kurtosis-ci"
        cl_type: op-node
        cl_image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:develop
        cl_extra_params:
          - "--l1.trustrpc=true"
      batcher_params:
        extra_params:
          - "--throttle-interval=0"
