ethereum_package:
  participants:
    - el_type: reth
      cl_type: lighthouse
optimism_package:
  chains:
    - participants:
      - el_type: op-geth
        el_image: "ghcr.io/ethereum-optimism/op-geth:kurtosis-ci"
        cl_type: op-node
        cl_image: "ghcr.io/ethereum-optimism/op-node:kurtosis-ci"
      - el_type: op-reth
        el_image: "ghcr.io/paradigmxyz/op-reth:kurtosis-ci"
        cl_type: op-node
        cl_image: "ghcr.io/ethereum-optimism/op-node:kurtosis-ci"
      batcher_params:
        extra_params:
          - "--throttle-interval=0"
      network_params:
        isthmus_time: "0"