ethereum_package:
  participants:
    - el_type: reth
      cl_type: lighthouse
optimism_package:
  op_contract_deployer_params:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-deployer:v0.0.11
  chains:
    - participants:
      - el_type: op-geth
        el_image: "ghcr.io/ethereum-optimism/op-geth:kurtosis-ci"
        cl_type: op-node
        cl_image: "ghcr.io/ethereum-optimism/op-node:kurtosis-ci"
        cl_extra_params:
          - "--l1.trustrpc=true"
      - el_type: op-reth
        el_image: "ghcr.io/paradigmxyz/op-reth:kurtosis-ci"
        cl_type: op-node
        cl_image: "ghcr.io/ethereum-optimism/op-node:kurtosis-ci"
        cl_extra_params:
          - "--l1.trustrpc=true"
      batcher_params:
        extra_params:
          - "--throttle-interval=0"
      network_params:
        isthmus_time_offset: 0